# Generated by Django 3.2.6 on 2022-01-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('describer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('publishedAt', models.DateTimeField()),
                ('channelTitle', models.CharField(blank=True, max_length=100)),
                ('categoryId', models.IntegerField()),
                ('thumbnail_url', models.CharField(max_length=100)),
            ],
        ),
    ]
